# Generated by Django 4.2.17 on 2025-01-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_off', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeoff',
            options={'verbose_name': 'отгул', 'verbose_name_plural': 'Добавить отгул'},
        ),
    ]
