# Generated by Django 4.2.17 on 2025-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_off', '0002_alter_timeoff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Коментарий'),
        ),
    ]
