# Generated by Django 4.2.17 on 2024-12-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_category_options_alter_events_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeOrNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_or_not', models.CharField(max_length=50, verbose_name='Платно или бесплатно')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='free_or_not',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.freeornot', verbose_name='Платно или нет'),
        ),
        migrations.AddField(
            model_name='freevisitors',
            name='free_or_not',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.freeornot', verbose_name='Платно или нет'),
        ),
    ]
