# Generated by Django 4.2.17 on 2024-12-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_freeornot_options_alter_events_preferential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='preferential',
            field=models.PositiveIntegerField(default=0, verbose_name='Льготно'),
        ),
        migrations.AlterField(
            model_name='freevisitors',
            name='preferential',
            field=models.PositiveIntegerField(default=0, verbose_name='Льготно'),
        ),
    ]
