# Generated by Django 4.2.17 on 2025-01-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_staff_tg_id_eventsplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsplan',
            options={'verbose_name': 'событие', 'verbose_name_plural': 'Занятость сотрудников'},
        ),
    ]
