# Generated by Django 4.2.17 on 2024-12-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория мероприятия')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='events.category', verbose_name='Подкатегория мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('date_start_event', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end_event', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Место проведения')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО сотрудника')),
                ('role', models.CharField(max_length=50, verbose_name='Должность')),
                ('actual', models.BooleanField(default=True, verbose_name='Действующий сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион или страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('VPN', models.PositiveIntegerField(default=0, verbose_name='ВПН')),
                ('adults', models.PositiveIntegerField(default=0, verbose_name='Взрослые')),
                ('university_students', models.PositiveIntegerField(default=0, verbose_name='Студенты ВУЗ')),
                ('college_students', models.PositiveIntegerField(default=0, verbose_name='Студенты колледж')),
                ('school', models.PositiveIntegerField(default=0, verbose_name='Школьники')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Докольники')),
                ('pensioners', models.PositiveIntegerField(default=0, verbose_name='Пенсионеры')),
                ('socially_supported_children', models.PositiveIntegerField(default=0, verbose_name='Социально опекаемые дети')),
                ('socially_supported_adult', models.PositiveIntegerField(default=0, verbose_name='Взрослые')),
                ('pushkn_cards', models.PositiveIntegerField(default=0, verbose_name='Пушкинская карта')),
                ('indigenous_children', models.PositiveIntegerField(default=0, verbose_name='Дети КМНС')),
                ('indigenous_adult', models.PositiveIntegerField(default=0, verbose_name='Взрослые КМНС')),
                ('autism_spectrum_children', models.PositiveIntegerField(default=0, verbose_name='РАС')),
                ('svo_children', models.PositiveIntegerField(default=0, verbose_name='Дети участников СВО')),
                ('preferential', models.CharField(max_length=200, verbose_name='Льготно')),
                ('Comments', models.CharField(max_length=600, verbose_name='Комментарий')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category', verbose_name='Категория мероприятия')),
                ('employee', models.ManyToManyField(related_name='events', to='events.staff', verbose_name='Сотрудник')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventlist', verbose_name='Название мероприятия')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.location', verbose_name='Место проведения')),
            ],
        ),
    ]
