# Generated by Django 4.2.17 on 2024-12-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_options_alter_eventlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию мероприятия', 'verbose_name_plural': 'Категории мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'путёвку', 'verbose_name_plural': 'Путёвки'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'сотрудника', 'verbose_name_plural': 'Сотрудники музея'},
        ),
        migrations.AddField(
            model_name='events',
            name='feedback',
            field=models.BooleanField(default=False, verbose_name='Положительный отзыв'),
        ),
        migrations.CreateModel(
            name='FreeVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион или страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('VPN', models.PositiveIntegerField(default=0, verbose_name='ВПН')),
                ('adults', models.PositiveIntegerField(default=0, verbose_name='Взрослые')),
                ('university_students', models.PositiveIntegerField(default=0, verbose_name='Студенты ВУЗ')),
                ('college_students', models.PositiveIntegerField(default=0, verbose_name='Студенты колледж')),
                ('school', models.PositiveIntegerField(default=0, verbose_name='Школьники')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Докольники')),
                ('pensioners', models.PositiveIntegerField(default=0, verbose_name='Пенсионеры')),
                ('socially_supported_children', models.PositiveIntegerField(default=0, verbose_name='Социально опекаемые дети')),
                ('socially_supported_adult', models.PositiveIntegerField(default=0, verbose_name='Взрослые')),
                ('pushkn_cards', models.PositiveIntegerField(default=0, verbose_name='Пушкинская карта')),
                ('indigenous_children', models.PositiveIntegerField(default=0, verbose_name='Дети КМНС')),
                ('indigenous_adult', models.PositiveIntegerField(default=0, verbose_name='Взрослые КМНС')),
                ('autism_spectrum_children', models.PositiveIntegerField(default=0, verbose_name='РАС')),
                ('svo_children', models.PositiveIntegerField(default=0, verbose_name='Дети участников СВО')),
                ('preferential', models.CharField(blank=True, max_length=200, null=True, verbose_name='Льготно')),
                ('feedback', models.BooleanField(default=False, verbose_name='Положительный отзыв')),
                ('Comments', models.CharField(blank=True, max_length=600, null=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_visitors', to='events.category', verbose_name='Категория мероприятия')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_visitors', to='events.eventlist', verbose_name='Название мероприятия')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_visitors', to='events.location', verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'индивидуальные посетители',
                'verbose_name_plural': 'Индивидуальные посетители',
            },
        ),
    ]
