# Generated by Django 4.2.17 on 2024-12-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_freeornot_events_free_or_not_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeornot',
            options={'verbose_name': 'платно или нет', 'verbose_name_plural': 'Платно или нет'},
        ),
        migrations.AlterField(
            model_name='events',
            name='preferential',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Льготно'),
        ),
        migrations.AlterField(
            model_name='freevisitors',
            name='preferential',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Льготно'),
        ),
    ]
